version: 0.2

env:
  secrets-manager:
    DB_URI: "db-uri"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "DB_URI=$DB_URI" >> .env

  # Run unit tests
  pre_build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/ -v
      - echo "Unit tests passed successfully."

  # Build application
  build:
    commands:
      - echo "Building Docker image..."
      - SAFE_TAG=$(echo $CODEBUILD_BUILD_ID | tr ':' '-')
      - echo "Using tag myapp:$SAFE_TAG"
      - docker build -t myapp:$SAFE_TAG .
      - echo "Saving Docker image as TAR..."
      - mkdir -p /tmp/artifact
      - docker save myapp:$SAFE_TAG -o /tmp/artifact/app_image.tar
      - ls -lh /tmp/artifact  # Verifica que el archivo existe

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Artifact prepared for S3 upload."

artifacts:
  files:
    - app_image.tar
  discard-paths: yes
  base-directory: /tmp/artifact
