version: 0.2

env:
  secrets-manager:
    DB_URI: "db-uri"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing python dependencies..."
      - pip install -r requirements.txt
      - echo "DB_URI=$DB_URI" >> .env

  # Run unit tests
  pre_build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/ -v
      - echo "Unit tests passed successfully."

  # Build application (TODO)
  build:
    commands:
      - echo "Building Docker image..."
